# Generated by Django 2.1.5 on 2019-02-03 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=django_fsm.FSMField(choices=[('New', 'New'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Fulfilled', 'Fulfilled'), ('Closed', 'Closed'), ('Chanceled', 'Chanceled'), ('Re Opened', 'Re Opened')], default=('New', 'New'), max_length=50),
        ),
    ]
