# Generated by Django 2.1.5 on 2019-02-05 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_auto_20190204_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='responsible',
        ),
        migrations.AddField(
            model_name='ticket',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
    ]
